# Generated by Django 2.2.6 on 2019-11-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_auto_20191104_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='resultado',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
