# Generated by Django 2.0.2 on 2019-10-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detalle',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
