# Generated by Django 2.0.2 on 2019-10-12 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_auto_20191012_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='project',
            name='fecha_modificacion',
        ),
    ]
