# Generated by Django 2.1.5 on 2019-10-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0005_auto_20191012_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
